detectors:
  DuplicateMethodCall:
    max_calls: 3
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    max_params: 5
  NestedIterators:
    max_allowed_nesting: 2
  RepeatedConditional:
    max_ifs: 3
  TooManyInstanceVariables:
    max_instance_variables: 5
  TooManyMethods:
    max_methods: 20
  TooManyStatements:
    max_statements: 10
  UtilityFunction:
    enabled: false
