#NO DOCKER
#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: <%= ENV['DB_USERNAME'] %>
#  password: <%= ENV['DB_PASSWORD'] %>
#  host: <%= ENV['DB_HOST'] %>
#  port: <%= ENV['DB_PORT'] %>

#development:
#  <<: *default
#  database: neo_surveys_development

#test:
#  <<: *default
#  database: neo_surveys_test

#production:
#  <<: *default
#  database: neo_surveys_production
#  username: neo_surveys
#  password: <%= ENV['NEO_SURVEYS_DATABASE_PASSWORD'] %>


#DOCKER
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 1qaz2wsx
  pool: 5

development:
  <<: *default
  database: neo_surveys_development

test:
  <<: *default
  database: neo_surveys_test